version: '3.9'

services:
  app:
    build: .
    restart: always
    # ports: 
    # - 9601:9601
    depends_on:
      - psqldb
    networks:
      - sessionServiceNetwork
      - garewaynestrabbit_gatewayNetwork
  psqldb:
    image: postgres:13
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql
    environment: 
      POSTGRES_PASSWORD: example
      POSTGRES_USER: keshox
      POSTGRES_DB: sessiondb
    networks:
      - sessionServiceNetwork
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    logging:
      driver: none
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.codovstvo
      PGADMIN_DEFAULT_PASSWORD: egor
    ports:
      - "9701:80"
    networks:
      - sessionServiceNetwork

networks:
  sessionServiceNetwork:
    driver: bridge
  garewaynestrabbit_gatewayNetwork:
    external: true
    
